#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'
#
spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    discovery:
      serviceId: ead-config-server
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ead-course-v2
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  rabbitmq:
#    addresses: amqps://lropqnph:edP_v86MF8bq-V0XFCgK8DO_4Mb6NUL4@shark.rmq.cloudamqp.com/lropqnph
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost